# Generated by Django 4.2.1 on 2023-05-09 12:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookpage",
            old_name="feed_image",
            new_name="book_image",
        ),
        migrations.RemoveField(
            model_name="bookpage",
            name="date",
        ),
        migrations.AddField(
            model_name="bookpage",
            name="book_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bookpagerelatedlink",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_links",
                to="author.authorpage",
            ),
        ),
    ]
